-- Скрипт сгенерирован Devart dbForge Studio for Oracle, Версия 3.5.185.0
-- Домашняя страница продукта: http://www.devart.com/ru/dbforge/oracle/studio
-- Дата скрипта: 29.10.2013 22:38:11
-- Версия сервера: Oracle Database 11g Express Edition Release 11.2.0.2.0 - Production
-- Версия клиента: 

CONNECT mioric/masterkey@localhost:1521/;


-- 
-- Установка схемы по умолчанию
--
ALTER SESSION SET CURRENT_SCHEMA = "MIORIC";

SET SQLBLANKLINES ON;
SET DEFINE OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/SYYYY HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF TZH:TZM';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
ALTER SESSION SET NLS_NCHAR_CONV_EXCP = FALSE;
ALTER SESSION SET TIME_ZONE = '+10:00';

--
-- Описание для последовательности SEQUENCE_METAATTRIBUTE_ID
--
CREATE SEQUENCE SEQUENCE_METAATTRIBUTE_ID
START WITH 1
INCREMENT BY 1;

--
-- Описание для последовательности SEQUENCE_METAITEM_ID
--
CREATE SEQUENCE SEQUENCE_METAITEM_ID
START WITH 1
INCREMENT BY 1;

--
-- Описание для последовательности SEQUENCE_METAOBJECT_ID
--
CREATE SEQUENCE SEQUENCE_METAOBJECT_ID
START WITH 1
INCREMENT BY 1;

--
-- Описание для последовательности SEQUENCE_METAPROPERTY_ID
--
CREATE SEQUENCE SEQUENCE_METAPROPERTY_ID
START WITH 1
INCREMENT BY 1;

--
-- Описание для таблицы METAOBJECT
--
CREATE TABLE METAOBJECT (
  ID   NUMBER(*, 0)       NOT NULL,
  NAME VARCHAR2(160 BYTE) NOT NULL,
  CONSTRAINT PK_METAOBJECT PRIMARY KEY (ID) USING INDEX (CREATE UNIQUE INDEX UK_METAOBJECT_ID ON METAOBJECT (ID) TABLESPACE MIORIC STORAGE (INITIAL 64 K
                                                                                                                                            NEXT 1 M
                                                                                                                                            MAXEXTENTS UNLIMITED) LOGGING)
)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

CREATE UNIQUE INDEX UK_METAOBJECT_NAME ON METAOBJECT (NAME)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE METAOBJECT IS 'Base object';

--
-- Описание для таблицы METAATTRIBUTETYPE
--
CREATE TABLE METAATTRIBUTETYPE (
  ID   NUMBER(*, 0)       NOT NULL,
  NAME VARCHAR2(160 BYTE) NOT NULL,
  CONSTRAINT KEY_METAATTRIBUTETYPE_ID UNIQUE (ID)
)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE METAATTRIBUTETYPE IS 'attribute type';

--
-- Описание для таблицы METAVALUE1
--
CREATE TABLE METAVALUE1 (
  PROPERTYID NUMBER(*, 0) NOT NULL,
  VALUE      NUMBER(*, 0)
)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

CREATE UNIQUE INDEX UK_METAVALUE1_PROPERTYID ON METAVALUE1 (PROPERTYID)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE METAVALUE1 IS 'integer';

--
-- Описание для таблицы METAVALUE2
--
CREATE TABLE METAVALUE2 (
  PROPERTYID NUMBER(*, 0) NOT NULL,
  VALUE      FLOAT(126)
)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

CREATE UNIQUE INDEX UK_METAVALUE2_PROPERTYID ON METAVALUE2 (PROPERTYID)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE METAVALUE2 IS 'DATE';

--
-- Описание для таблицы METAVALUE3
--
CREATE TABLE METAVALUE3 (
  PROPERTYID NUMBER(*, 0) NOT NULL,
  VALUE      TIMESTAMP(6)
)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

CREATE UNIQUE INDEX UK_METAVALUE3_PROPERTYID ON METAVALUE3 (PROPERTYID)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

--
-- Описание для таблицы METAVALUE4
--
CREATE TABLE METAVALUE4 (
  PROPERTYID NUMBER(*, 0) NOT NULL,
  VALUE      TIMESTAMP(6)
)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

CREATE UNIQUE INDEX UK_METAVALUE4_PROPERTYID ON METAVALUE4 (PROPERTYID)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE METAVALUE4 IS 'DATE TIME';

--
-- Описание для таблицы METAVALUE5
--
CREATE TABLE METAVALUE5 (
  PROPERTYID NUMBER(*, 0) NOT NULL,
  VALUE      VARCHAR2(1024 BYTE)
)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

CREATE UNIQUE INDEX UK_METAVALUE5_PROPERTYID ON METAVALUE5 (PROPERTYID)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE METAVALUE5 IS 'STRING';

--
-- Описание для таблицы METAVALUE6
--
CREATE TABLE METAVALUE6 (
  PROPERTYID NUMBER(*, 0) NOT NULL,
  VALUE      CLOB
)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

CREATE UNIQUE INDEX UK_METAVALUE6_PROPERTYID ON METAVALUE6 (PROPERTYID)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE METAVALUE6 IS 'TEXT';

--
-- Описание для таблицы METAVALUE7
--
CREATE TABLE METAVALUE7 (
  PROPERTYID NUMBER(*, 0) NOT NULL,
  VALUE      CHAR(1 BYTE)
)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

CREATE UNIQUE INDEX UK_METAVALUE7_PROPERTYID ON METAVALUE7 (PROPERTYID)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE METAVALUE7 IS 'BOOLEAN';

--
-- Описание для таблицы METAVALUE8
--
CREATE TABLE METAVALUE8 (
  PROPERTYID NUMBER(*, 0) NOT NULL,
  VALUE      BLOB
)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

CREATE UNIQUE INDEX UK_METAVALUE8_PROPERTYID ON METAVALUE8 (PROPERTYID)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE METAVALUE8 IS 'DATA';

--
-- Описание для таблицы METAVALUE9
--
CREATE TABLE METAVALUE9 (
  PROPERTYID NUMBER(*, 0) NOT NULL,
  VALUE      NUMBER(*, 0)
)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

CREATE UNIQUE INDEX UK_METAVALUE9_PROPERTYID ON METAVALUE9 (PROPERTYID)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE METAVALUE9 IS 'LINK';

--
-- Описание для таблицы METAVALUE10
--
CREATE TABLE METAVALUE10 (
  PROPERTYID NUMBER(*, 0) NOT NULL,
  VALUE      NUMBER(*, 0)
)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

CREATE INDEX IDX_METAVALUE10_PROPERTYID ON METAVALUE10 (PROPERTYID)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE METAVALUE10 IS 'LINK TO MANY';

--
-- Описание для таблицы METAATTRIBUTE
--
CREATE TABLE METAATTRIBUTE (
  ID                  NUMBER(*, 0),
  METAOBJECTID        NUMBER(*, 0)       NOT NULL,
  NO                  NUMBER(*, 0)       NOT NULL,
  METAATTRIBUTETYPEID NUMBER(*, 0)       NOT NULL,
  NAME                VARCHAR2(160 BYTE) NOT NULL,
  CONSTRAINT PK_METAATTRIBUTE PRIMARY KEY (ID),
  CONSTRAINT FK_ATTRIBUTE_OBJECT_ID FOREIGN KEY (METAOBJECTID)
  REFERENCES METAOBJECT (ID),
  CONSTRAINT FK_METAATTRIBUTE_ID FOREIGN KEY (METAATTRIBUTETYPEID)
  REFERENCES METAATTRIBUTETYPE (ID)
)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

CREATE UNIQUE INDEX UK_METAATTRIBUTETYPEID ON METAATTRIBUTE (METAATTRIBUTETYPEID)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE METAATTRIBUTE IS 'attribute';

--
-- Описание для таблицы METAITEM
--
CREATE TABLE METAITEM (
  ID         NUMBER(*, 0) NOT NULL,
  OBJECTID   NUMBER(*, 0) NOT NULL,
  DATESTART  TIMESTAMP(6),
  DATEFINISH TIMESTAMP(6),
  CONSTRAINT PK_METAITEM PRIMARY KEY (ID),
  CONSTRAINT FK_METAITEM_METAOBJECT_ID FOREIGN KEY (OBJECTID)
  REFERENCES METAOBJECT (ID)
)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE METAITEM IS 'item';

--
-- Описание для таблицы METAPROPERTY
--
CREATE TABLE METAPROPERTY (
  ID          NUMBER(*, 0) NOT NULL,
  ITEMID      NUMBER(*, 0) NOT NULL,
  ATTRIBUTEID NUMBER(*, 0) NOT NULL,
  DATESTART   TIMESTAMP(6),
  DATEFINISH  TIMESTAMP(6),
  CONSTRAINT PK_METAPROPERTY PRIMARY KEY (ID),
  CONSTRAINT FK_METAPROPERTY_METAITEM_ID FOREIGN KEY (ITEMID)
  REFERENCES METAITEM (ID),
  CONSTRAINT FK_PROPERTY_ATTRIBUTE FOREIGN KEY (ATTRIBUTEID)
  REFERENCES METAATTRIBUTE (ID)
)
TABLESPACE MIORIC
STORAGE (INITIAL 64 K
         NEXT 1 M
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE METAPROPERTY IS 'property';

-- 
-- Вывод данных для таблицы METAOBJECT
--

-- Таблица MIORIC.METAOBJECT не содержит данных

-- 
-- Вывод данных для таблицы METAATTRIBUTETYPE
--
INSERT INTO METAATTRIBUTETYPE VALUES
(1, 'INTEGER');
INSERT INTO METAATTRIBUTETYPE VALUES
(2, 'DOUBLE');
INSERT INTO METAATTRIBUTETYPE VALUES
(3, 'DATE');
INSERT INTO METAATTRIBUTETYPE VALUES
(4, 'DATETIME');
INSERT INTO METAATTRIBUTETYPE VALUES
(5, 'STRING');
INSERT INTO METAATTRIBUTETYPE VALUES
(6, 'TEXT');
INSERT INTO METAATTRIBUTETYPE VALUES
(7, 'BOOLEAN');
INSERT INTO METAATTRIBUTETYPE VALUES
(8, 'DATA');
INSERT INTO METAATTRIBUTETYPE VALUES
(9, 'LINK');
INSERT INTO METAATTRIBUTETYPE VALUES
(10, 'LINKMANY');

-- 
-- Вывод данных для таблицы METAVALUE1
--

-- Таблица MIORIC.METAVALUE1 не содержит данных

-- 
-- Вывод данных для таблицы METAVALUE2
--

-- Таблица MIORIC.METAVALUE2 не содержит данных

-- 
-- Вывод данных для таблицы METAVALUE3
--

-- Таблица MIORIC.METAVALUE3 не содержит данных

-- 
-- Вывод данных для таблицы METAVALUE4
--

-- Таблица MIORIC.METAVALUE4 не содержит данных

-- 
-- Вывод данных для таблицы METAVALUE5
--

-- Таблица MIORIC.METAVALUE5 не содержит данных

-- 
-- Вывод данных для таблицы METAVALUE6
--

-- Таблица MIORIC.METAVALUE6 не содержит данных

-- 
-- Вывод данных для таблицы METAVALUE7
--

-- Таблица MIORIC.METAVALUE7 не содержит данных

-- 
-- Вывод данных для таблицы METAVALUE8
--

-- Таблица MIORIC.METAVALUE8 не содержит данных

-- 
-- Вывод данных для таблицы METAVALUE9
--

-- Таблица MIORIC.METAVALUE9 не содержит данных

-- 
-- Вывод данных для таблицы METAVALUE10
--

-- Таблица MIORIC.METAVALUE10 не содержит данных

-- 
-- Вывод данных для таблицы METAATTRIBUTE
--

-- Таблица MIORIC.METAATTRIBUTE не содержит данных

-- 
-- Вывод данных для таблицы METAITEM
--

-- Таблица MIORIC.METAITEM не содержит данных

-- 
-- Вывод данных для таблицы METAPROPERTY
--

-- Таблица MIORIC.METAPROPERTY не содержит данных

--
-- Описание для триггера METAATTRIBUTE_INSERT
--
CREATE OR REPLACE TRIGGER METAATTRIBUTE_INSERT
  BEFORE INSERT
  ON METAATTRIBUTE
  FOR EACH ROW
BEGIN
  :new.id := SEQUENCE_METAATTRIBUTE_ID.NEXTVAL;
END;

/

--
-- Описание для триггера METAITEM_INSERT
--
CREATE OR REPLACE TRIGGER METAITEM_INSERT
  BEFORE INSERT
  ON METAITEM
  FOR EACH ROW
BEGIN
  :new.id := SEQUENCE_METAITEM_ID.NEXTVAL;
END;

/

--
-- Описание для триггера METAOBJECT_INSERT
--
CREATE OR REPLACE TRIGGER METAOBJECT_INSERT
  BEFORE INSERT
  ON METAOBJECT
  FOR EACH ROW
BEGIN
  :new.id := SEQUENCE_METAOBJECT_ID.NEXTVAL;
END;

/

--
-- Описание для триггера METAPROPERTY_INSERT
--
CREATE OR REPLACE TRIGGER METAPROPERTY_INSERT
  BEFORE INSERT
  ON METAPROPERTY
  FOR EACH ROW
BEGIN
  :new.id := SEQUENCE_METAPROPERTY_ID.NEXTVAL;
END;

/

-- 
-- Установка схемы по умолчанию
--
DECLARE
  p VARCHAR2(255);
BEGIN 
  SELECT USER INTO p FROM DUAL;
  EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = ' || p;
END;
/